### ISSUE TITLE
Instructions on how to run on Windows

### ISSUE THREAD

**Issue by Shinigami92** [Sleavely/satisfactory-savegame-prometheus-exporter#7]
The following worked for me:

```ps1
docker run -d --name satisfactory-savegame-prometheus-exporter -p 9772:9772 -v C:\Users\shinigami\AppData\Local\FactoryGame\Saved\SaveGames\server:/savegames:ro -e SAVEGAME_LOCATION=/savegames sleavely/satisfactory-savegame-prometheus-exporter:latest
```

Then I configured my prometheus.yml with:

```yml
  - job_name: "satisfactory-savegame-exporter"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9772", "host.docker.internal:9772"]
```

@Sleavely feel free to use this somehow as docs
